sudo: required

language: clojure

services:
  - docker

before_install:
- docker pull wurstmeister/zookeeper
- docker pull wurstmeister/kafka
- docker-compose up -d
- docker ps -a

jdk:
  - oraclejdk8

script: "lein monolith each do clean, check, midje, install"
