sudo: required

language: clojure

services:
  - docker

before_install:
- docker pull wurstmeister/zookeeper
- docker pull wurstmeister/kafka
- docker run -d -p 127.0.0.1:2181:2181 wurstmeister/zookeeper
- docker run -d -p 127.0.0.1:9092:9092 wurstmeister/kafka
- docker ps -a

jdk:
  - oraclejdk8

script: "lein monolith each do clean, check, midje, install"
